[project]
name = "14_Biolit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "duckdb>=1.1.3",
    "duckdb-engine>=0.15.0",
    "ipykernel>=6.29.5",
    "ipython>=8.31.0",
    "ipython-sql>=0.5.0",
    "jupysql>=0.10.17",
    "jupyterlab>=4.5.5",
    "marimo>=0.18.4",
    "matplotlib>=3.10.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pillow>=12.0.0",
    "plotly>=6.5.0",
    "polars>=1.36.1",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "requests>=2.32.3",
    "ruff>=0.14.10",
    "structlog>=25.5.0",
    "tqdm>=4.67.3",
    "transformers>=5.2.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
